version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "8003:80"
        restart: on-failure
        environment:
            VIRTUAL_HOST: life.418.ovh
            VIRTUAL_PORT: 8003
            LETSENCRYPT_HOST: life.418.ovh
            LETSENCRYPT_EMAIL: avingtier@gmail.com
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        networks:
            - shared-proxy

volumes:
    db_data: {}

networks:
    shared-proxy:
        external: true